import React,{useEffect,useRef,useState} from 'react';
import {Link,NavLink} from 'react-router-dom';
import {Zap,Home,Crown,Swords,User,ArrowUpRight,Heart,X,Clock,Coins,MapPin} from 'lucide-react';
import {jobTitleGenerator} from '../utils/jobTitleGenerator.js';
import {days} from '../data/jobs.js';
export const money=n=>Math.round(n).toLocaleString('ko-KR');
export function HunterLogo(){return <Link className="logo" to="/home"><span className="logo-icon"><Zap fill="currentColor"/></span><span>SSS <b>ALBA</b><small>HUNTER SYSTEM</small></span></Link>;}
export function BottomNav(){return <nav className="nav">{[['/home',Home,'HOME'],['/ranking',Crown,'RANKING'],['/battle',Swords,'BATTLE'],['/my',User,'MY']].map(([p,I,t])=><NavLink key={p} to={p}><I size={19}/><span>{t}</span></NavLink>)}</nav>;}
export function RankBadge({grade,large=false}){return <span className={`rank rank-${grade.replace('+','plus')} ${large?'large':''}`}>{grade}</span>;}
export function CombatPower({power}){const [n,setN]=useState(power);useEffect(()=>{let f;const start=performance.now();const run=t=>{setN(Math.round(power*Math.min(1,(t-start)/650)));if(t-start<650)f=requestAnimationFrame(run);};f=requestAnimationFrame(run);return()=>cancelAnimationFrame(f);},[power]);return <div className="power"><small><Swords size={13}/> COMBAT POWER</small><strong>{money(n)}</strong></div>;}
export function StatBar({label,value}){return <div className="statbar"><div><span>{label}</span><b>{Math.round(value)}</b></div><div className="track"><i style={{width:`${value}%`}}/></div></div>;}
export function StatPanel({job}){const names={gold:'GOLD · 시급',schedule:'SCHEDULE · 시간표',distance:'MOBILITY · 이동',transport:'COST · 교통비',workload:'STAMINA · 업무강도',real:'REAL PAY · 진짜 시급'};return <div className="stats-grid">{Object.entries(names).map(([k,n])=><StatBar key={k} label={n} value={job.stats[k]}/>)}</div>;}
export function QuestCard({job:j,index,featured=false,onBattle,saved,onSave,onReason}){return <article className={`quest-card ${featured?'featured':''} ${j.grade.startsWith('SSS')?'sss-card':''}`}><div className="card-top"><span className="eyebrow">{index!=null?`RANK ${String(index+1).padStart(2,'0')} / `:''}QUEST #{j.id.padStart(3,'0')}</span><button className={`icon-button ${saved?'saved':''}`} aria-label={saved?'찜 해제':'퀘스트 찜'} aria-pressed={saved} onClick={()=>onSave(j.id)}><Heart size={19} fill={saved?'currentColor':'none'}/></button></div><div className="quest-heading"><div><span className="category">{j.category} · {j.type==='short'?'단기 퀘스트':'장기 퀘스트'}</span><h2><Link to={`/job/${j.id}`}>{j.name}</Link></h2><p className="muted">{jobTitleGenerator(j)}</p></div><RankBadge grade={j.grade} large={featured}/></div><CombatPower power={j.power}/><div className="metrics"><div><small><Coins/> REWARD</small><b>{money(j.hourlyPay)}<em>원</em></b></div><div><small><Clock/> TRAVEL</small><b>{j.commuteMinutes}<em> MIN</em></b></div><div><small><MapPin/> COST</small><b>{money(j.transportCost)}<em>원</em></b></div></div><div className="real-row"><span>REAL REWARD <b>{money(j.realPay)}원</b></span><span>FIT <b>{j.fit}%</b></span></div><div className="tags"><span>#{j.commuteMinutes<=10?'학교앞퀘스트':'원정퀘스트'}</span><span>#{j.transportCost===0?'교통비0원':'이동비반영'}</span><button onClick={()=>onReason(j)}>왜 {j.grade}야? ↗</button></div><div className="card-actions"><Link className="button" to={`/job/${j.id}`}>QUEST DETAILS <ArrowUpRight size={17}/></Link><button className="secondary" onClick={()=>onBattle(j.id)}><Swords size={16}/> BATTLE</button></div></article>;}
export function ReasonModal({job:j,onClose}){const ref=useRef();useEffect(()=>{ref.current.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><button className="icon-button close" onClick={onClose} aria-label="닫기"><X/></button><span className="eyebrow">SYSTEM EXPLANATION</span><h2>{j.analysisContext?`${j.grade} 등급 분석`:`너한테 ${j.grade}인 이유`}</h2>{j.analysisContext&&<p className="analysis-context">{j.analysisContext} 기준 랭킹</p>}<p>{j.name}의 실제 조건을 분석했어.</p><StatPanel job={j}/><div className="buff">+ 시간표 적합도 {j.fit}%<br/>+ 편도 이동 {j.commuteMinutes}분 · 왕복 교통비 {money(j.transportCost)}원<br/>+ {days.filter((_,i)=>j.days.includes(i)).join('·')} {j.start}:00–{j.start+j.shiftHours}:00</div><div className="debuff">확인해봐 · {j.caution}<br/>{j.fit<80?'수업 또는 가능 요일과 겹치는 시간이 있어.':'근무 전 상세 일정을 꼭 확인해봐.'}</div><small className="muted">POWER는 7개 항목의 개인별 가중 평균이야. 실제 채용 공고가 아닌 시연용 데이터야.</small></dialog>;}
export function Timetable({value,onChange}){return <div className="timetable"><div/><>{days.slice(0,5).map(d=><b key={d}>{d}</b>)}</>{Array.from({length:13},(_,i)=>i+9).map(h=><React.Fragment key={h}><span>{String(h).padStart(2,'0')}</span>{days.slice(0,5).map((d,i)=>{const key=`${i}-${h}`,selected=value.includes(key);return <button key={key} type="button" className={selected?'class-time':'free-time'} aria-label={`${d}요일 ${h}시 ${selected?'수업 있음':'빈 시간'}`} aria-pressed={selected} onClick={()=>onChange(selected?value.filter(x=>x!==key):[...value,key])}>{selected?'수업':'·'}</button>;})}</React.Fragment>)}</div>;}
