import React,{useState,useMemo} from 'react';
import {Routes,Route,Navigate,useNavigate,useLocation} from 'react-router-dom';
import {HunterLogo,BottomNav,ReasonModal} from './components/UI.jsx';
import Effects from './components/Effects.jsx';
import Login from './pages/Login.jsx';
import Onboarding,{Landing} from './pages/Onboarding.jsx';
import {Home,JobDetail,MyPage} from './pages/Board.jsx';
import RankingHub from './pages/RankingHub.jsx';
import Battle from './pages/Battle.jsx';
import {jobs as rawJobs} from './data/jobs.js';
import {analyze,defaultUser} from './utils/scoring.js';
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback;}catch{return fallback;}}
function useStored(key,initial){const [value,set]=useState(()=>read(key,initial));const [error,setError]=useState(false);function update(next){set(old=>{const v=typeof next==='function'?next(old):next;try{localStorage.setItem(key,JSON.stringify(v));setError(false);}catch{setError(true);}return v;});}return[value,update,error];}
export default function App(){const [stored,setUser,e1]=useStored('sss-user-v2',defaultUser),[saved,setSaved,e2]=useStored('sss-saved-v1',[]),[battles,setBattles,e3]=useStored('sss-battles-v1',0);const user={...defaultUser,...stored};const [pair,setPair]=useState(['1','5']),[reason,setReason]=useState(null);const navigate=useNavigate(),location=useLocation();const jobs=useMemo(()=>rawJobs.map(j=>analyze(j,user)).sort((a,b)=>b.power-a.power),[JSON.stringify(user)]);function onBattle(id,other){setPair([id,other|| (id==='5'?'1':'5')]);navigate('/battle');}function onSave(id){setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);}const props={jobs,user,saved,onSave,onBattle,onReason:setReason};const intro=!user.profileReady||location.pathname==='/'||location.pathname.includes('onboarding')||location.pathname==='/setup';return <><Effects/><header><HunterLogo/>{!intro&&<BottomNav/>}<span className="header-status"><i/> SYSTEM ONLINE <small>DEMO v1.0</small></span></header>{(e1||e2||e3)&&<div role="status" className="storage-warning">브라우저 저장 공간을 사용할 수 없어. 현재 탭에서는 계속 사용할 수 있지만 새로고침하면 변경이 사라질 수 있어.</div>}<main key={location.pathname} className={intro?'intro-main':'app-main'}>{!user.profileReady?<Login user={user} setUser={setUser}/>:<Routes><Route path="/" element={<Navigate to={user.complete?'/home':'/onboarding/type'} replace/>}/><Route path="/onboarding/type" element={<Onboarding step={0} user={user} setUser={setUser}/>}/><Route path="/onboarding/preferences" element={<Onboarding step={1} user={user} setUser={setUser}/>}/><Route path="/onboarding/title" element={<Onboarding step={2} user={user} setUser={setUser}/>}/><Route path="/onboarding/categories" element={<Onboarding step={3} user={user} setUser={setUser}/>}/><Route path="/setup" element={<Onboarding step={4} user={user} setUser={setUser}/>}/><Route path="/home" element={<Home {...props}/>}/><Route path="/ranking" element={<RankingHub {...props}/>}/><Route path="/job/:id" element={<JobDetail {...props}/>}/><Route path="/battle" element={<Battle jobs={jobs} pair={pair} setPair={setPair} onComplete={()=>setBattles(n=>n+1)}/>}/><Route path="/my" element={<MyPage {...props} battles={battles}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}</main><footer><span>SSS ALBA © 2026</span><span>YOUR TIME. YOUR GOLD. YOUR QUEST.</span><span>유형 랭킹은 가상 공고 · 실제 공고는 출처 표시</span></footer>{reason&&<ReasonModal job={reason} onClose={()=>setReason(null)}/>}</>;}
